name: Rapport de bug mobile
description: Rapporter un nouveau bug
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: "## Décrivez le bug rencontré"
  - type: textarea
    id: what-happened
    attributes:
      label: Que s'est-il passé ?
      placeholder: Dites nous ce qu'il s'est passé
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Donnez nous plus d'informations pour reproduire et corriger ce bug"
  - type: dropdown
    id: os-mobile
    attributes:
      label: Sur quel OS le bug s'est-il produit ?
      multiple: true
      options: ["Android", "iOS"]
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: Pouvez-vous préciser la/les version(s) de l'OS
  - type: input
    id: test-account-login
    attributes:
      label: Quel compte utilisateur peut-on utiliser pour reproduire ce bug ?
      placeholder: jdoe@gmail.com
  - type: input
    id: test-account-password
    attributes:
      label: Quel est le mot de passe du compte de test mentionné ci-dessus ?
  - type: textarea
    id: logs
    attributes:
      label: Logs techniques
      description: Uniquement les logs techniques issus de la console de développement (mise en forme automatique, inutile de faire des retours à la ligne)
      render: shell
  - type: markdown
    attributes:
      value: "## Attendu pour la correction de ce bug"
  - type: textarea
    id: what-should-happen
    attributes:
      label: Qu'est-ce qui aurait du se passer ?
      placeholder: On aurait du pouvoir faire / voir ...
    validations:
      required: true
