name: Rapport de bug web
description: Rapporter un nouveau bug web
title: "[Bug] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: "## Décrivez le bug rencontré"
  - type: textarea
    id: what-happened
    attributes:
      label: Que s'est-il passé ?
      description: N'hésitez pas à lister méthodiquement les étapes de reproduction du bug et le résultat obtenu.
      placeholder: Dites nous ce qu'il s'est passé
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Donnez nous plus d'informations pour reproduire et corriger ce bug"
  - type: input
    id: app-version
    attributes:
      label: Sur quelle version de l'application ce bug s'est-il produit ?
  - type: dropdown
    id: browser
    attributes:
      label: Sur quel navigateur le bug s'est-il produit ?
      multiple: true
      options: ["Firefox", "Chrome", "Safari", "Microsoft Edge", "Autre"]
    validations:
      required: true
  - type: input
    id: test-account-login
    attributes:
      label: Quel compte utilisateur peut-on utiliser pour reproduire ce bug ?
      placeholder: jdoe@gmail.com
  - type: input
    id: test-account-password
    attributes:
      label: Quel est le mot de passe du compte de test mentionné ci-dessus ?
  - type: textarea
    id: logs
    attributes:
      label: Logs techniques
      description: Uniquement les logs techniques issus de la console de développement (mise en forme automatique, inutile de faire des retours à la ligne)
      render: shell
  - type: markdown
    attributes:
      value: "## Attendus pour la résolution de ce bug"
  - type: textarea
    id: what-should-happen
    attributes:
      label: Qu'est-ce qui aurait du se passer ?
      placeholder: On aurait du pouvoir faire / voir ...
    validations:
      required: true
