name: Rapport de bug
description: Rapporter un nouveau bug
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: "## Décrivez le bug rencontré"
  - type: textarea
    id: what-happened
    attributes:
      label: Que s'est-il passé ?
      placeholder: Dites nous ce qu'il s'est passé
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Donnez nous plus d'informations pour reproduire et corriger ce bug"
  - type: input
    id: test-account-login
    attributes:
      label: Quel compte utilisateur peut-on utiliser pour reproduire ce bug ?
      placeholder: jdoe@gmail.com
  - type: input
    id: test-account-password
    attributes:
      label: Quel est le mot de passe du compte de test mentionné ci-dessus ?
  - type: textarea
    id: logs
    attributes:
      label: Logs techniques
      render: shell
  - type: markdown
    attributes:
      value: "## Attendu pour la correction de ce bug"
  - type: textarea
    id: what-should-happen
    attributes:
      label: Qu'est-ce qui aurait du se passer ?
      placeholder: On aurait du pouvoir faire / voir ...
    validations:
      required: true
