name: User Story
description: Créer une nouvelle User Story
title: "[Feature] "
labels: ["feature", "triage"]
body:
  - type: markdown
    attributes:
      value: |
      ## Définition de l'User Story
      > Rappel: Une bonne User Story respecte les caractéristiques réunies sous le sigle **INVEST**.
      > **Indépendante** : une User Story est indépendante vis-à-vis des |autres User Stories du backlog. Idéalement, elle se suffit à elle même pour éviter les dépendances avec d'autres User Stories. Car toute dépendance génère des problématiques de planification et de tests. 
      > **Négociable** : une User Story est un support de discussion en vue d’une amélioration du besoin initial. Elle peut être modifiée, on parle d'affinage jusqu'à son intégration dans une itération ou Sprint. Généralement, on considère qu'elle est affinée lorsqu'elle répond aux critères de la "Définition of Ready" établie par l'équipe. 
      > **Valorisable** : la réalisation d’une User Story doit rendre un service à l’utilisateur. Elle n'a de sens que si elle apporte une valeur métier. 
      > **Estimable** : une User Story doit être bien définie pour être facilement estimable, quel que soit votre mode d'estimation. Si l'équipe n'est pas en capacité de l'estimer, c'est souvent que votre User Story manque de clarté.
      > **Small** : une User Story doit être réalisable sur un sprint, soit suffisamment petite ou découpée de telle manière à pouvoir être déployée sur un seul sprint et minimiser les effets tunnels sur plusieurs sprints. Cherchez donc à découper vos User Stories le plus finement possible. Mieux vaut créer deux petites User Stories, qu'une grande.
      > **Testable**: une User Story doit raconter une histoire dont les critères d'acceptabilité et les tests doivent découler de manière évidente pour faciliter sa validation. "
  - type: textarea
    id: content
    attributes:
      label: Décrivez la fonctionnalité attendue
      placeholder: "En tant que [rôle, utilisateur], Je veux [besoin, action] afin de [bénéfice, valeur métier]"
      value: "En tant que [rôle, utilisateur], Je veux [besoin, action] afin de [bénéfice, valeur métier]"
  - type: textarea
    id: end-user-goal
    attributes:
      label:  Objectif de l'utilisateur final
      placeholder: ""
      value: ""
  - type: textarea
    id: end-business-goal
    attributes:
      label: Objectif métier final
      placeholder: ""
      value: ""
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Critères d'acceptation / scénario de test
      description: "La définition d’un scénario de test en Gherkin se fait selon trois étapes clés : Given, When Then."
      placeholder: |
        1. Étant donné que je dispose d’un compte utilisateur « jdoe@gmail.com »
        2. Quand j’accède à la page d’authentification /auth.html
        3. Et que je saisis mon identifiant « jdoe@gmail.com » dans le champ « Login »
        4. Et que je saisie mon mot de passe dans le champ « Password »
        5. Et que je clique sur le bouton « Connexion » du formulaire
        6. Alors je suis authentifié sur le site
        7. Et je suis redirigé vers la page « Mon compte » à l’URL /mon-compte.html 
  